name: PR Size Labeler

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-size-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          configuration-path: './github/config.yml'